allowBuilds:
  sharp: false
  unrs-resolver: false

minimumReleaseAgeExclude:
  - '@next/*'
  - '@oxfmt/*'
  - '@oxlint/*'
  - '@oxlint-tsgolint/*'
  - next
  - oxfmt
  - oxlint
  - oxlint-tsgolint
  - react@19.2.8
  - react-dom@19.2.8
